<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GamePlatform.Application\GamePlatform.Application.csproj" />
      <ProjectReference Include="..\GamePlatform.Domain\GamePlatform.Domain.csproj" />
      <ProjectReference Include="..\GamePlatform.Persistence\GamePlatform.Persistence.csproj" />
    </ItemGroup>

</Project>
